##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.box_download_options = {"ssl-revoke-best-effort" => true}

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-box-rocky9-pbspro"
    v.memory = "1024"

    v.customize [
      "modifyvm",           :id,
      "--cableconnected1",  "on",
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
    ]
  end

  config.vm.provision("root", type: "shell",
                      path: "provision/root.sh",
                      privileged: true)
  config.vm.provision("install-pbs", type: "shell",
                      path: "provision/install-pbs.sh",
                      privileged: false)
  config.vm.provision("cleanup", type: "shell",
                      path: "provision/cleanup.sh",
                      privileged: true)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
